Replace TouchableHighlight with TouchableOpacity
FaridSafi/react-native-google-places-autocomplete pull request #648
Opened 2020-11-07 17:35 UTC by MS0015

In scoroll view onpress doesn't regonize but TouchableOpacity did

2020-11-08 21:28 UTC, bell-steven commented
Can you describe the problem you are trying to solve with this change?

2020-11-09 01:37 UTC, bell-steven requested changes

2020-11-09 01:37 UTC, bell-steven commented on GooglePlacesAutocomplete.js
>            }
`underlayColor` is not available on `<TouchableOpacity />`

2020-11-09 02:34 UTC, MS0015 commented
TouchableHighlight not regonize touch event in react-native-modalize even scrollViewProps={{ keyboardShouldPersistTaps: 'handled' }} set but when change to TouchableOpacity it regonize touch event so that i changed 

you can check it and i you have othe alternative please suggest

2020-11-09 03:03 UTC, bell-steven commented
Can you please open an issue with a full reproduction? 
To the best of my knowledge, there is technically no reason that `<TouchableOpacity />` should work over `<TouchableHighlight />`.

2020-11-09 15:13 UTC, closed without merging