loader to show that the google places api is loading places
FaridSafi/react-native-google-places-autocomplete pull request #704
Opened 2021-03-16 07:58 UTC by DanishWajid

2021-03-16 14:09 UTC, bell-steven requested changes
Thanks for the PR.

A few things to keep in mind:
1) we have loader in the `renderRow` function, we probably don't want to have both.
2) Aside from `loadingText`, I really want to avoid adding any more props.
3) How can we make sure this isn't a breaking change, while at the same time improving the activityLoader behavior and making it more customizable at the same time.
4) I you can run yarn lint, I would appreciate it.

2021-03-16 14:09 UTC, bell-steven commented on GooglePlacesAutocomplete.js
> +    return <ActivityIndicator animating={true} color={props.loaderColor} size='small' />;
Let's see if we can add this to the styles.loader prop.

2021-03-16 14:45 UTC, DanishWajid commented
ok let me fix the issues.

On Tue, Mar 16, 2021 at 7:09 PM Steven Bell ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the PR.
>
> A few things to keep in mind:
>
>    1. we have loader in the renderRow function, we probably don't want to
>    have both.
>    2. Aside from loadingText, I really want to avoid adding any more
>    props.
>    3. How can we make sure this isn't a breaking change, while at the
>    same time improving the activityLoader behavior and making it more
>    customizable at the same time.
>    4. I you can run yarn lint, I would appreciate it.
>
> ------------------------------
>
> In GooglePlacesAutocomplete.js
> <https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/704#discussion_r595193873>
> :
>
> > @@ -124,6 +124,7 @@ export const GooglePlacesAutocomplete = forwardRef((props, ref) => {
>    };
>
>    const [stateText, setStateText] = useState('');
> +  const [loading, setLoader] =useState(false);
>
> just for consistencies sake, can this be const [loading, setLoading] =
> useState(false);
> ------------------------------
>
> In GooglePlacesAutocomplete.js
> <https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/704#discussion_r595194184>
> :
>
> > @@ -141,10 +142,6 @@ export const GooglePlacesAutocomplete = forwardRef((props, ref) => {
>      };
>      // eslint-disable-next-line react-hooks/exhaustive-deps
>    }, []);
> -  useEffect(() => {
> -    // Update dataSource if props.predefinedPlaces changed
> -    setDataSource(buildRowsFromResults([]))
> -  }, [props.predefinedPlaces])
>
> Why is this being removed?
> ------------------------------
>
> In GooglePlacesAutocomplete.js
> <https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/704#discussion_r595195023>
> :
>
> > @@ -529,10 +527,12 @@ export const GooglePlacesAutocomplete = forwardRef((props, ref) => {
>    };
>
>    // eslint-disable-next-line react-hooks/exhaustive-deps
> -  const debounceData = useMemo(() => debounce(_request, props.debounce), [props.query]);
> +  const debounceData = useMemo(() => debounce(_request, props.debounce), []);
>
> props.query was added yesterday, any reason you are removing it here
> (same as above)?
> ------------------------------
>
> In GooglePlacesAutocomplete.js
> <https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/704#discussion_r595198306>
> :
>
> > @@ -547,7 +547,7 @@ export const GooglePlacesAutocomplete = forwardRef((props, ref) => {
>    };
>
>    const _getRowLoader = () => {
> -    return <ActivityIndicator animating={true} size='small' />;
> +    return <ActivityIndicator animating={true} color={props.loaderColor} size='small' />;
>
> Let's see if we can add this to the styles.loader prop.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/704#pullrequestreview-613275962>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIIVYGQ33PIYV4IUEJ2E2ILTD5RDPANCNFSM4ZIA5GOA>
> .
>

2021-03-17 08:52 UTC, DanishWajid commented
I have made some changes.

1- Used the old _renderLoader function made some changes.
2-The three new props (loaderColor, styles.loadingText and  loadingText) are still there because I think it's useful.
3- I change the ` const [loading, setLoader] =useState(false)`  to  `const [loading, setLoading] = useState(false)`.
4- According to my test cases, I don't think it's breaking change. You can double-check.
5- The new code removed in my previous commit is merged again (i have cloned the repo earlier but the changes are merged yesterday that's why it's removed by mistake).

2021-03-17 14:04 UTC, bell-steven approved these changes

2021-03-17 14:04 UTC, bell-steven commented on GooglePlacesAutocomplete.js
> +  const _renderLoader = ({ isLoading = false } = {}) => {
Where are you setting `isLoading?`

2021-03-17 14:08 UTC, DanishWajid commented
isLoading functionality is implemented previously for _renderRow. I didn't set it just destructured it to avoid code-breaking.

2021-03-17 14:20 UTC, merged