Allow Persistent Results
FaridSafi/react-native-google-places-autocomplete pull request #705
Opened 2021-03-22 12:11 UTC by haydncomley

Results from the search can be made to persist after the blur event has been fired and focus from the input is lost.
This is helpful in a variety of situations where the on screen keyboard needs to be hidden or focus pulled elsewhere with the results from the search still visible.

2021-03-22 13:43 UTC, bell-steven requested changes
Can you add `keepResultsAfterBlur: false` to the default props.

2021-03-23 13:29 UTC, bell-steven approved these changes

2021-03-23 13:30 UTC, merged

2021-03-23 13:30 UTC, bell-steven commented
Thanks for the PR!

2021-03-23 14:08 UTC, haydncomley commented
No problem at all - i'm just glad my first PR experience was a nice one so thank you too!

2021-04-21 22:03 UTC, ezemgaray commented
Useful and I think it reduces the autocomplete billing per request !! waiting for release!! @bell-steven @haydncomley

2021-04-22 14:10 UTC, haydncomley commented
@ezemgaray 

This was completed and merged into master - should be available to use right now as long as you've pulled the last version I believe.

2021-04-22 16:08 UTC, bell-steven commented
It hasn't been release on npm yet, I am waiting for another commit before releasing.

2021-08-02 02:14 UTC, bell-steven commented
Sorry for the delay in getting this out.
Released as v2.3.0